### PR TITLE
fix(labwhere-client): handle request timeouts

### LINKED ISSUE #5685: Y26-128 - [BUG] LabwhereClient handle timeout exception
**Describe the bug**
Several errors for RestClient::Exceptions::OpenTimeout occurred in labwhere_receptions#create during a period where labwhere was inaccessible. This error was not being caught and caused a 500 error for users instead of informing them that labwhere was down.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page 'labwhere_receptions'
2. Attempt to scan in labware with a hanging labwhere instance.
    - May be difficult to recreate. Potentially add a binding.pry in labwhere will do this.

**Expected behaviour**
User is shown an error that labwhere is inaccessible

### PR DESCRIPTION
**Pull request by BenTopping**
Closes #5685

#### Changes proposed in this pull request

- Handle request timeouts to prevent 500 errors when labwhere is unresponsive.

### CODE REVIEW

File: lib/lab_where_client.rb [hunk 1]
```diff
@@ -26,21 +26,21 @@ def parse_json(str)
 
     def get(instance, target)
       parse_json(RestClient.get(path_to(instance, target)))
-    rescue Errno::ECONNREFUSED, RestClient::NotFound => e
+    rescue Errno::ECONNREFUSED, RestClient::NotFound, RestClient::RequestTimeout => e
```
Comment (BenTopping) [inline lib/lab_where_client.rb:29]: RestClient combined with our scan error setup has pretty ugly error handling. Ideally we would catch everything [RestClient::RequestFailed](https://github.com/rest-client/rest-client?tab=readme-ov-file#exceptions-see-httpwwww3orgprotocolsrfc2616rfc2616-sec10html) and utilise the response message but unfortunately this has a few nasty edge cases so leaving it as a simple addition for this bug,

Comment (StephenHulme) [reply lib/lab_where_client.rb:29]: In previous restclient testing I also had cases where a no-connection resulted in a 500 error being returned. I dug through the code for a couple hours and decided it was easier to convert it to Faraday. I would recommend that path for future work.

**Review by StephenHulme — APPROVED** [review]
