### PR TITLE
Y25-179 - Bulk submission upload error messages

### LINKED ISSUE #4717: Y25-179 - [BUG] uploading bulk submission file fails without true reason
When  uploading bulk submission file, where samples have not been accessioned, this fails with
'There was a problem when building your submissions'

https://sequencescape.psd.sanger.ac.uk/bulk_submissions/new

Reported in [SR-23137](https://sanger.freshservice.com/a/tickets/23137)

Should report the error rescued

(additional info: SSR fed back that the samples did not have accessions and this was due to the study not having been accessioned)

Note: Testing the accessioning service requires this to be turned on in UAT/Training envs which at present it isn't

Changes to deployment project required (`@ay6` in Slack @psd-user-requests 05/03/2015 13:00) 

config template: `roles/deploy_sequencescape/templates/config.rb.j2`

`accession_url` and `accession_view_url` for different environments: 
[same for all environments and `disable_accession_check: true` for both UAT and Training. We might change URLs to EBI test URLs to enable it for all environments to ensure isolation from production]
`roles/deploy_sequencescape/vars/main.yml`

credentials: 
[same used for all environments, we might change them per environment to ensure isolation from production]
```
environments/uat/group_vars/all/vault.yml
environments/training/group_vars/all/vault.yml
environments/production/group_vars/all/vault.yml
```

### PR DESCRIPTION
**Pull request by BenTopping**
Closes #4717 

#### Changes proposed in this pull request

- Changes location for new bulk submission RecordInvalid error handling.
- Restores `form.semantic_errors` which was removed from here: https://github.com/sanger/sequencescape/pull/4660
  - This is required for errors on base (bulk submission) to appear on the form.
  - This was originally removed to fix a duplicate error message bug: https://github.com/sanger/sequencescape/issues/4579. I have confirmed this change does not break this behaviour and users only see 1 set of error messages.
- Adds test to bulk_submission model spec for accessioning checks.

#### Additional notes
- There are no test cases for bulk submission controller tests but I have added one to the model that covers the logic change.
- To test this locally you need to set `configatron.disable_accession_check = false`

### CODE REVIEW

File: app/models/bulk_submission.rb [hunk 1]
```diff
@@ -206,6 +206,8 @@ def process # rubocop:todo Metrics/CyclomaticComplexity
               ] = "Submission #{submission.id} built (#{submission.orders.count} orders)"
             rescue Submission::ProjectValidation::Error => e
               errors.add :spreadsheet, "There was an issue with a project: #{e.message}"
+            rescue ActiveRecord::RecordInvalid => e
+              errors.add :base, e.message
```
Comment (dasunpubudumal) [inline app/models/bulk_submission.rb:210]: `e.message` prints a bit of weird messages like "Validation failed: Orders request options read length for the LO flow cell kit the user can select a Read Length of 150". I don't know if we need to sanitise them but I guess they are comprehendable.

**Review by dasunpubudumal — APPROVED** [review]

File: app/models/bulk_submission.rb (hunk 1 above)
Comment (BenTopping) [reply app/models/bulk_submission.rb:210]: Yeah I agree its a bit ugly. I will have a look see if there is a quick win but I think this is a symptom of how we/rails handle error messages generally.

Comment (dasunpubudumal) [reply app/models/bulk_submission.rb:210]: Yeah I feel like unless we override something it would be a bit difficult to get around with. But I don't know if we should be overriding anything.
