### PR TITLE
Bug fix for ordering issue

### LINKED ISSUE #5199: Y25-535 - [BUG] Ordering of tables changed after datatables upgrade
**Describe the bug**
The ordering of rows in tables in Sequencescape has changed after the datatables package was upgraded recently (https://github.com/sanger/sequencescape/issues/4727). Some mentioned as particularly impactful are:
- Samples table on a labware page (and probably elsewhere - e.g. receptacle) - not ordered by well
- Manifests table not ordered newest to oldest (Study > manifests)

Ideally, the ordering on all tables would be put back to how it was before. 

**RT Ticket Number**
Raised by Liz C in #psd-techadmin in Slack

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by dasunpubudumal**
Closes #5199

There is _some_ reference to a stable ordering change in the [Changelog](https://datatables.net/upgrade/2#Stable-ordering). I'm not 100% sure how it impacted our case.

#### Changes proposed in this pull request

- Set `order: []` to preserve the default ordering.

```diff
$(function () {
  document.querySelectorAll(cssSelectors.DefaultConfig).forEach((table) => {
--- new DataTable(table, defaults);
+++ new DataTable(table, { ...defaults, order: [] });
  });
```
- The input data to the tables are already ordered by the backend.
    1. Sample manifests are ordered in the controller at [`app/controllers/studies_controller.rb`](https://github.com/sanger/sequencescape/blob/develop/app/controllers/studies_controller.rb#L320).
    2. Labware samples are ordered in the corresponding labware views. For plates, the view is [`app/views/assets/samples_partials/_plate_samples.erb`](https://github.com/sanger/sequencescape/blob/develop/app/views/assets/samples_partials/_plate_samples.erb#L29).

image

image

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

**Review by sabrine33 — APPROVED** [review]

File: app/frontend/datatables/tableSortable.js [hunk 1]
```diff
@@ -13,11 +13,11 @@ import DataTable from "datatables.net-bs4";
 
 $(function () {
   document.querySelectorAll(cssSelectors.DefaultConfig).forEach((table) => {
-    new DataTable(table, defaults);
+    new DataTable(table, { ...defaults, order: [] });
```
Comment (harrietc52) [inline app/frontend/datatables/tableSortable.js:16]: How come passing [] preserves the existing order?! Great that it works though

Comment (dasunpubudumal) [reply app/frontend/datatables/tableSortable.js:16]: I guess it's one of those changes they've introduced into 2.x.
