### PR TITLE
Cherrypick pipelines will set batch to nil

### LINKED ISSUE #3105: Remove requests functionality broken for cherrypicking
When you get the option to 'fail or remove' items
in the cherrypicking pipeline, the requests are not
actually removed from the batch if you check 'remove'

### PR DESCRIPTION
**Pull request by JamesGlover**
Cherrypick pipelines were not removing the requests
from the batch. This restores the functionality.

Fixes #3105

### CODE REVIEW

File: app/models/cherrypick_for_pulldown_pipeline.rb [hunk 1]
```diff
@@ -14,12 +14,6 @@ def post_release_batch(batch, _user)
     batch.release_pending_requests
   end
 
-  def update_detached_request(batch, request)
-    # We do not need to do any of the default behaviour:
-    # 1. The requests should just be detached, not blocked
-    # 2. The assets are not removed because they are not considered unused
-  end
-
```
Comment (JamesGlover) [inline app/models/cherrypick_for_pulldown_pipeline.rb:22]: Moved onto superclass

File: app/models/cherrypick_pipeline.rb [hunk 2]
```diff
@@ -31,10 +31,4 @@ def post_release_batch(batch, _user)
     batch.release_pending_requests
     batch.output_plates.each(&:cherrypick_completed)
   end
-
-  def update_detached_request(batch, request)
-    # We do not need to do any of the default behaviour:
-    # 1. The requests should just be detached, not blocked
-    # 2. The assets are not removed because they are not considered unused
-  end
 end
```
Comment (JamesGlover) [inline app/models/cherrypick_pipeline.rb:34]: Moved onto superclass

**Review by pjvv — APPROVED** [review]

**Review by andrewsparkes — APPROVED** [review]
