### PR TITLE
Extend scoped on V2 tube API

### LINKED ISSUE #3067: GPL-888 BUG - Timeouts in GBS pool tube creation
This represents the sequencescape work required for https://github.com/sanger/limber/issues/634

Original issue:
**Describe the bug**
GBS MiSeq Pool tube creation was returning a 404 after 60s, due to the tube search taking too long to return. I've temporarily increased the timeouts in nginx to relieve the problem. But should do the following:

1) Add a 503 error template to avoid the confusion of a 404
2) Update to use the V2 tube endpoint to improve performance
3) Consider further improvements (such as asynchonous calls)

**RT Ticket Number**
#712129

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

### PR DESCRIPTION
**Pull request by JamesGlover**
Add scopes to allow V2 tube API to be used in place of
V1 tube searches

Closes #3067

Changes proposed in this pull request:

*
*
* ...

### CODE REVIEW

File: app/resources/api/v2/tube_resource.rb [hunk 1]
```diff
@@ -40,10 +40,11 @@ class TubeResource < BaseResource
       filter :barcode, apply: ->(records, value, _options) { records.with_barcode(value) }
       filter :uuid, apply: ->(records, value, _options) { records.with_uuid(value) }
       filter :purpose_name, apply: (lambda do |records, value, _options|
-        purpose = Purpose.find_by(name: value)
+        purpose = Purpose.where(name: value)
         records.where(plate_purpose_id: purpose)
```
Comment (JamesGlover) [inline app/resources/api/v2/tube_resource.rb:44]: This adjustment lest us pass in either a single purpose name, or an array of them.

File: app/models/concerns/single_receptacle_labware.rb [hunk 2]
```diff
@@ -22,8 +22,6 @@ module SingleReceptacleLabware
     delegate :aliquots, :aliquots=, to: :receptacle
     delegate :concentration, :concentration=, to: :receptacle
     # Delegate for the moment, update once things are working
-    delegate :transfer_requests_as_target, :transfer_requests_as_source, to: :receptacle
-    # Delegate for the moment, update once things are working
```
Comment (KatyTaylor) [inline app/models/concerns/single_receptacle_labware.rb:26]: don't need this because it's on Labware model?

**Review by KatyTaylor — APPROVED** [review]

File: app/models/concerns/single_receptacle_labware.rb (hunk 2 above)
Comment (JamesGlover) [reply app/models/concerns/single_receptacle_labware.rb:26]: Yep, was only ever supposed to stay there while I refactored, a mistake to have left it in.
