### PR TITLE
Y25-277 - Fix label printing issues when re-printing labels for batches

### LINKED ISSUE #4869: Y25-277 - [BUG] Fix label printing issues when re-printing labels for batches
**Describe the bug**

When [printing labels](https://uat.sequencescape.psd.sanger.ac.uk/batches/4/print_labels) from [batch summary page](https://uat.sequencescape.psd.sanger.ac.uk/batches/4), the client gets an internal server error.

Underneath, it's a `NoMethodError`.

```
A NoMethodError occurred in batches#print_barcodes:

  undefined method `name_for_label' for an instance of Lane::Labware
  lib/label_printer/label/batch_tube.rb:16:in `first_line'
```

This was discovered by a user (long read).

**RT Ticket Number**
If applicable

**To Reproduce**

Please refer to the attached links in the story description.

**Expected behaviour**

The user should be able to print out the barcodes.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

### PR DESCRIPTION
**Pull request by borhara**
Closes #4869 

#### Changes proposed in this pull request

- Checking whether the stock is present before grabbing the tube name and set an alternative name for the label

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

File: lib/label_printer/label/batch_tube.rb [hunk 1]
```diff
@@ -13,7 +13,11 @@ def initialize(options)
       end
 
       def first_line(tube)
-        stock.present? ? tube.name : tube.name_for_label
+        if stock.present?
+          tube.name
+        else
+          tube.respond_to?(:name_for_label) ? tube.name_for_label : tube.name
```
Comment (dasunpubudumal) [inline lib/label_printer/label/batch_tube.rb:19]: Nice. I'm kind of suspicious of why this `primary_sample&.shorten_sanger_sample_id.presence` check existed in the first place. We are effectively bypassing that check with this change.

**Review by dasunpubudumal — COMMENTED** [review]
A small comment.

File: lib/label_printer/label/batch_tube.rb (hunk 1 above)
Comment (harrietc52) [reply lib/label_printer/label/batch_tube.rb:19]: Might be worth adding a small unit test for this

**Review by harrietc52 — APPROVED** [review]
