### PR TITLE
Y26-065 - Hide automated submission templates

### LINKED ISSUE #5593: Y26-065 - [BUG] Automated Submissions - hide automated submission templates from dropdowns
**Describe the bug**
As SSRs we would like the 'automated' versions of submission template hidden from display in selection boxes to avoid confusion and mistakes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to either create submission or bulk submission pages in Sequencescape
2. See the automated versions of submission templates in the drop down select boxes

**Expected behaviour**
You should not see or be able to use the 'automated' submission templates when making manual submissions.

**Additional context**
The submission template for the Bioscan 'automated' library prep (and 3 other automated templates for other pipelines) appear in the Sequencescape submission templates dropdown select options when the SSR selects a template for manually creating a submission. 
These need to be filtered out of the lists. 

Dependency - the Bioscan one is being used as a workaround due to another bug. Story https://github.com/sanger/limber/issues/2726. So that one should be done first.

Filtering these out could either be done by creating a new flag in submission templates that indicate  'is_automated?' or less robustly by looking for the word 'automated' in the template name.

### PR DESCRIPTION
**Pull request by BenTopping**
Closes #5593

#### Changes proposed in this pull request

- Adds 'automated' column to submission templates, seeding for existing automated submission templates.
- Adds 'automated: false' as a criteria for submission template visibility.
- Adds submission template spec file.
    - There are a couple bits I haven't touched but at least there is some coverage now.
    - It also highlighted the sequencing? method didn't work 😅

### CODE REVIEW

File: db/migrate/20260410121704_add_automated_submission_template_column.rb [hunk 1]
```diff
@@ -0,0 +1,21 @@
+# frozen_string_literal: true
+
+# Adds an 'automated' column to submission templates to differentiate templates that are used for automated submissions.
+class AddAutomatedSubmissionTemplateColumn < ActiveRecord::Migration[8.0]
+  def change
+    add_column :submission_templates, :automated, :boolean, default: false, null: false
+
+    # Automated submission templates at the time of this migration
+    existing_automated_template_names = [
```
Comment (andrewsparkes) [inline db/migrate/20260410121704_add_automated_submission_template_column.rb:9]: neat how you've done that migration

File: app/models/submission_template.rb [hunk 2]
```diff
@@ -27,15 +27,15 @@ class SubmissionTemplate < ApplicationRecord # rubocop:todo Metrics/ClassLength
...
+  scope :visible, -> { order(product_line_id: :asc).where(superceded_by_id: LATEST_VERSION, automated: false) }
   scope :include_product_line, -> { includes(:product_line) }
 
   def self.grouped_by_product_lines
     visible.include_product_line.group_by { |t| t.product_line.try(:name) || 'General' }
   end
 
   def visible
-    superceded_by_id == LATEST_VERSION
+    superceded_by_id == LATEST_VERSION && !automated
```
Comment (andrewsparkes) [inline app/models/submission_template.rb:38]: so does this work to hide the templates from all submission selection dropdowns? (submission screen, bulk submission screen, possibly re-sequencing screen)

**Review by andrewsparkes — APPROVED** [review]
Looks good to me, thanks.
Did you check both normal and bulk submission screens, and the request additional sequencing screen? I assume they all come off the model so should be fine.

File: app/models/submission_template.rb (hunk 2 above)
Comment (BenTopping) [reply app/models/submission_template.rb:38]: Yep all nicely abstracted.
See [bulk submissions](https://github.com/sanger/sequencescape/blob/develop/app/controllers/bulk_submissions_controller.rb#L45)
See [standard submissions](https://github.com/sanger/sequencescape/blob/develop/app/models/submission/submission_creator.rb#L195)
Request additional sequencing uses request_types as opposed to submission templates.
